version: '3.9'
services:
  frontend:
    build: ./
    container_name: app_calculator
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE